// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// DC_para
List DC_para(NumericMatrix& mat, int k);
RcppExport SEXP _scDHA_DC_para(SEXP matSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix& >::type mat(matSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(DC_para(mat, k));
    return rcpp_result_gen;
END_RCPP
}
// jaccard_coeff
NumericMatrix jaccard_coeff(NumericMatrix idx);
RcppExport SEXP _scDHA_jaccard_coeff(SEXP idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type idx(idxSEXP);
    rcpp_result_gen = Rcpp::wrap(jaccard_coeff(idx));
    return rcpp_result_gen;
END_RCPP
}
// non_zero_index
arma::uvec non_zero_index(arma::mat& data);
RcppExport SEXP _scDHA_non_zero_index(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(non_zero_index(data));
    return rcpp_result_gen;
END_RCPP
}
// normalize_data_dense
arma::sp_mat normalize_data_dense(arma::mat& data);
RcppExport SEXP _scDHA_normalize_data_dense(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(normalize_data_dense(data));
    return rcpp_result_gen;
END_RCPP
}
// normalize_data_sparse
arma::sp_mat normalize_data_sparse(arma::sp_mat& data);
RcppExport SEXP _scDHA_normalize_data_sparse(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat& >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(normalize_data_sparse(data));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_scDHA_DC_para", (DL_FUNC) &_scDHA_DC_para, 2},
    {"_scDHA_jaccard_coeff", (DL_FUNC) &_scDHA_jaccard_coeff, 1},
    {"_scDHA_non_zero_index", (DL_FUNC) &_scDHA_non_zero_index, 1},
    {"_scDHA_normalize_data_dense", (DL_FUNC) &_scDHA_normalize_data_dense, 1},
    {"_scDHA_normalize_data_sparse", (DL_FUNC) &_scDHA_normalize_data_sparse, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_scDHA(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
