# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DC_para <- function(mat, k = 10L) {
    .Call('_scDHA_DC_para', PACKAGE = 'scDHA', mat, k)
}

jaccard_coeff <- function(idx) {
    .Call('_scDHA_jaccard_coeff', PACKAGE = 'scDHA', idx)
}

non_zero_index <- function(data) {
    .Call('_scDHA_non_zero_index', PACKAGE = 'scDHA', data)
}

normalize_data_dense <- function(data) {
    .Call('_scDHA_normalize_data_dense', PACKAGE = 'scDHA', data)
}

normalize_data_sparse <- function(data) {
    .Call('_scDHA_normalize_data_sparse', PACKAGE = 'scDHA', data)
}

